# -*- coding: utf-8 -*-
"""Data 301-Hello-World

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbPdViyNtdAWtVViAQWEvqHjA6vvgeki
"""

a = 10
b = 10

a+b